SEED = 13
# Default window used for sequence building (e.g., embeddings/MLM).
WINDOW_HOURS = 24
BIN_SIZE_HOURS = 6

# LOS-specific windowing for downstream classification.
LOS_WINDOW_HOURS = 1
LOS_BIN_SIZE_HOURS = 1
MAX_LEN = 256
VOCAB_LIMIT = 8000
MASK_PROB = 0.15
SPECIAL_TOKENS = ["[PAD]", "[CLS]", "[SEP]", "[MASK]", "[ADMIT]", "[DISCH]"]

BATCH_SIZE = 64
NUM_EPOCHS = 20
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 0.01
PRINT_EVERY = 50
GRAD_CLIP_NORM = 1.0

HIDDEN_SIZE = 256
NUM_HIDDEN_LAYERS = 3
NUM_ATTENTION_HEADS = 8
INTERMEDIATE_SIZE = 1024
MAX_POSITION_EMBEDDINGS = 512
HIDDEN_DROPOUT_PROB = 0.2
ATTN_DROPOUT_PROB = 0.2
